### ISSUE TITLE
[FEATURE] Allow removing or sorting existing codes

### ISSUE THREAD

**Issue by oscardelgado** [4f77616973/Wristkey#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 4f77616973** [comment]
Tapping and holding site name lets you modify or delete a login.

**Comment by oscardelgado** [comment]
Sorry, I mean sorting the entries inside one of the accounts.

**Comment by 4f77616973** [comment]
Oh alright, I'll reopen this issue then.

**Comment by 4f77616973** [comment]
I'm curious as to what "sorting entries" means. Are you talking about reordering the order in which accounts appear in the app?

**Comment by oscardelgado** [comment]
No, I will explain better:

I have imported my codes from the Google Authenticator app, and I have 7
codes. For example:

- App1 111 111
- App2 222 222
- ...
- App7 777 777

And I use the App 7 more often than others. I would like it to appear first
in the list.
