### ISSUE TITLE
[BUG] The app doesn't open when lock by pattern is set on the watch

### ISSUE THREAD

**Issue by oscardelgado** [4f77616973/Wristkey#3]
**Describe the bug**
The app doesn't open when lock by pattern is set on the watch.

Wear OS

**To Reproduce**

1. I have enabled Pattern unlock in the device settings.
2. I try to open Wristkey, and it asks me for my pattern.
3. I enter it, and the app closes and I am left on the Wear OS menu to select apps.

**Expected behavior**
The app should open when I enter my pattern.

**Screenshots**
N/A

**Watch:**
 - Watch Name and model number: Mobvoi TicWatch E D15J
 - OS: 2.31
 - Wristkey version 1.3.1
 
Home app 2.51.0...
Google Play Services 21.33.14
Android 8.0.0
Android security patch August 1st 2018

**Smartphone (if applicable):**
 - Device: iPhone 6S Plus
 - OS: iOS14.8

Thanks!

**Comment by nelsonlobo99** [comment]
You can use a PIN instead of a pattern.

**Comment by IsakTheHacker** [comment]
Hi!
I am having a similar problem with the Galaxy Watch 4 which I think could be relatable. For me the app closes no matter if I have pattern unlock turned on or off.

However, 1/15 times it actually succeeds in opening the app and the app runs like normal.

Do you guys think these problems are related or do you have an idea of what is going on?
Thanks in advance!

**Comment by 4f77616973** [comment]
I think this may be an issue with the Wear OS SDK or Wear OS itself. It's especially strange that it works sometimes and doesn't at other times.

**Comment by 4f77616973** [comment]
Hey there, I'm rewriting parts of this app to make it Wear OS 3.0 friendly. I think I've fixed this bug. I'll be merging to `master` shortly, but you can try it on the `wear-3.0-redesign` branch anyway try it and tell me if the bug is fixed.
