### ISSUE TITLE
[BUG] i was not able import the file

### ISSUE THREAD

**Issue by Pruthviraj-Guddu** [4f77616973/Wristkey#46]
**Describe the bug**
run-as: package not debuggable: zeroxfourf.wristkey

I have installed the app on my wearOS watch [Samsung watch 7]. using the below command 
`adb -s 192.168.5.20:46287 install app-release.apk `

I have copied the file aegis app to my watch using the below command 
`% adb -s 192.168.5.20:46287  shell run-as run-as zeroxfourf.wristkey cp /data/local/tmp/aegis-export-plain-6211495091.json  files/`

now the issue is the app is **not debuggable**
run-as: package not debuggable: zeroxfourf.wristkey

this worked in the the previous version of the app

**Comment by 0x4f53** [comment]
You'll need to clone the project and build it as a **debug** app in Android Studio. I am planning to add a feature to detect this in the next version (as explained in #42 ), and a pipeline to build both debug and stable versions of the app for this purpose. For now, I can't seem to find the time to add all these things.

Feel free to make a pull request if it's urgent.
