### ISSUE TITLE
How to install? 

### ISSUE THREAD

**Issue by Offerel** [4f77616973/Wristkey#5]
Sorry to ask this stupid question, but I'm new to Wear OS. First I'm really happy to find a open source app for Wear OS. This seems to be not the standard for this OS. On Android, I can use F-droid but I haven't found as of yet such an store for Wear OS.

How can I install your app on the watch? I have tried to install the apk on the phone, in hope this transferred it to the watch, but this doesn't work.

**Comment by 4f77616973** [comment]
Hello. You can follow [this XDA guide](https://forum.xda-developers.com/t/how-to-sideload-apks-onto-android-wear-watch.3726276/) that shows you how to sideload APKs onto your watch.
