### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by youarenot667543** [4f77616973/Wristkey#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Watch:**
 - Watch Name and model number: [e.g. LG G Watch W100]
 - OS: [e.g. Wear OS 2.2]
 - Wristkey version [e.g. v1.1]

**Smartphone (if applicable):**

**Additional context**

**Comment by 4f77616973** [comment]
I'm assuming you made this one on accident. I'll close it to keep things clean.
